language: php

php:
  - 7.1

env:
  - SYMFONY_VERSION=3.2.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update

install: composer update --prefer-dist --no-interaction

script:
  - phpunit --coverage-text